spring:
  application:
    name: api-service
  cloud:
    zookeeper:
     connect-string: localhost:2181

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

debug: false

server.port: 9696

#ebean
ebean.db.ddl.generate: true
ebean.db.ddl.run: true
datasource.db.username: user
datasource.db.password: password
datasource.db.databaseUrl: jdbc:mysql://127.0.0.1:3306/purepurr
datasource.db.databaseDriver: com.mysql.cj.jdbc.Driver

#flyway
flyway.locations: filesystem:db/migration
flyway.url: jdbc:mysql://127.0.0.1:3306/purepurr
flyway.user: user
flyway.password: password